# First Person%
# Forces First Person controls wherever possible

# WARNING
# To hit Olga, you must be holding R1 when you fire

# Available modes are:
# 1 = Strafing controls (left=strafe, right=turn & aim)
# 2 = Turning controls (left=move & left/right aim, right=aim) 
# 3 = Turning controls (left=move & left/right aim, right=aim)

# Toggle is an input mask (see MGS2.dist.ini for the full list)
# that will toggle first person on and off (R1 by default)
# The game must be paused for it to work

[FirstPerson]
Enabled=Yes
#Mode=1
#Toggle=0002