# Actions
# Lets you define keyboard shortcuts to perform certain actions

# Uncomment a category (e.g. [Actions.Trainer]) and set Enabled=Yes to enable it

# KeyCode is the trigger button (e.g. "T")'s win32 key code in hexadecimal format (e.g. 54)
# See this webpage for the full list (the "Value" column)
# https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

# ModifierKeys represents a combination of the modifier keys Shift/Ctrl/Alt
# 0 = nothing, 1 = Shift, 2 = Ctrl, 3 = Ctrl+Shift, 4 = Alt
# 5 = Alt+Shift, 6 = Ctrl+Alt, 7 = Ctrl+Alt+Shift

[Actions]
Enabled=Yes

# Launch MGS2 Trainer (default Ctrl+T)
# With Trainer version a46 or higher, its Soft Reset function will be disabled if ASI Soft Reset is enabled
# Path should be the full location of MGS2Trainer.exe
#[Actions.Trainer]
#Enabled=No
#KeyCode=54
#ModifierKeys=2
#Path=C:\Path\To\MGS2Trainer.exe

# Launch an application
# For multiple actions, create more categories, e.g. [Actions.Application.2] etc.
#[Actions.Application.1]
#Enabled=No
#KeyCode=
#ModifierKeys=
#Path=
