# Soft Reset
# Goes back to the main menu when L1+L2+R1+R2+Start is pressed

# WARNING
# Do not use the trainer on its default hotkey profile, and this mod, together
# The game will probably crash when using the pad shortcut to soft-reset
#
# You must disable the trainer's ResetGame pad shortcut
# by editing HotKeys.json in a text editor:
#
# Find:
# "pad": [ "L1", "R1", "L2", "R2", "Start" ]
# and replace it with:
# "pad": []


# You must not be in a codec when pressing the shortcut, or this will not work


[SoftReset]
Enabled=Yes