# Caution%
# Forces non-normal alert states when entering an area

# Available AlertLevels:
# 0 = No Alert (all difficulties act like VE)
# 1 = Alert (usually quickly depletes down to Evasion)
# 2 = Evasion (behaves like Easy+ when moving between areas)
# 3 = Caution (always at least in Caution, but can be in Alert/Evasion as normal)
# Alert/Evasion/Caution in AlertLevels 1 and 2 can be escaped as normal

[Caution]
Enabled=Yes
#AlertLevel=3