# PS2 Controls
# Changes inputs to match those on the PlayStation 2
# Most notably, Circle and X are swapped for Confirm and Cancel

# This mod is not complete - most of Missions is unchanged and may be confusing

[PS2Controls]
Enabled=Yes