# New Game Information
# Shows information about New Game settings and other important settings on screen

# If ShowWarnings=Yes, any active mods which would invalidate a speedrun
# will also be shown
# If ShowNotices=Yes, other non-runbreaking mods that may not be wanted will be shown

# If ShowNewGame=Yes, New Game will be shown when not starting a NG+/++ run
# If ShowNGOID=Yes, Not Game Over If Discovered will be shown on easier difficulties

[NewGameInfo]
Enabled=Yes
#ShowWarnings=Yes
#ShowNotices=Yes
#ShowNewGame=No
#ShowNGOID=No