# Save Location Changer
# Changes the location of the save game directory

# To change the save location on the fly, press Ctrl+O to open a selection dialog
# If already in a save/load menu, you'll need to exit and reenter it

# Use L1/L2 and R1/R2 in save/load menus to go directly to the first/last save


# WARNING
# If you already have the SaveGameLocationChanger.asi mod
# (V's Fix 1.7; V's Fix 1.8 non-GoG)
# this mod's location changing functions will not work
# If you want to use them, you should delete SaveGameLocationChanger.asi

# If ChangeDirectory=Yes, BaseDirectory and SavePath will be used to set
# the initial save location

# KeyCode and ModifierKeys change the keyboard shortcut for the selection dialog
# See MGS2.Actions.ini for more information about these settings

# BaseDirectory (optional) can choose certain starting points
# where the path may be different on different machines
# It can be set to one of the following:
# Desktop        (C:\Users\<user>\Desktop)
# Documents      (C:\Users\<user>\Documents)
# LocalAppData   (C:\Users\<user>\AppData\Local)
# Profile        (C:\Users\<user>)
# RoamingAppData (C:\Users\<user>\AppData\Roaming)
# MGS2           (<path_to_mgs2_install>\bin)
# None           (nothing - you should put the entire path in SavePath)

# SavePath will be added to the end of the BaseDirectory
# You don't need a slash at the start or end of the path, or an opening .\

# If you know the exact path you want, set BaseDirectory=None
# and SavePath to that path, e.g. C:\Users\egrapefruits24\Dropbox\MGS2
# Relative paths are fine.


[SaveLocation]
Enabled=Yes
#ChangeDirectory=No
#KeyCode=4F
#ModifierKeys=2

# Same as V's Fix (1.7/1.8 non-GoG) (default)
#BaseDirectory=Documents
#SavePath=My Games\METAL GEAR SOLID 2 SUBSTANCE

# Same as V's Fix (1.8 GoG) and original game
#BaseDirectory=MGS2
#SavePath=..\savedata