# Turbo Display
# Displays the current turbo status on screen

# Works with XInputPlus (use ShowXInput=Yes)
# or the Turbo module in this plugin (use ShowXInput=No)

# If SystemSound=Yes, turbo sounds will be assigned to the system notifications
# audio session, instead of using the game's session.
# This lets you change the turbo volume independently in Windows' volume mixer

# The profile settings in [TurboDisplay] are for when turbo is disabled
# They will be inherited by [TurboDisplay.Profile.1] below
# but you can override individual settings

# PlaySound is the full path to a WAV file. If it's left empty, no sound is used

[TurboDisplay]
Enabled=Yes
#ShowXInput=Yes
#TextVisible=No
#TextContent=TURBO
#TextPosX=622
#TextPosY=457
#TextAlign=1
#TextColor=B4B4B4
#PlaySound=

# Profile 1 is your XInputPlus turbo, if ShowXInput is enabled above
# Otherwise, it's the internal [Turbo.Profile.1] in MGS2.Turbo.ini
[TurboDisplay.Profile.1]
TextVisible=Yes
#TextContent=
#TextPosX=
#TextPosY=
#TextAlign=
#TextColor=
#PlaySound=