# Timer Display
# Shows a game timer on screen

# Precision: The number of digits shown for fractions of a second (0, 1 or 2)

# You can use the customisation tool at https://mgs.w00ty.com/mgs2/overlay/#customise
# to preview different positions and colours, before changing them in this file

# TextFormat lets you change the text that appears
# Change it to any text, inserting %s where you want to time to go

# Uncomment [Timer.ExpectedTime] to show a predicted time during the credits for Plant

[Timer]
Enabled=Yes
#TextVisible=Yes
#Precision=2
#TextPosX=621
#TextPosY=2
#TextAlign=1
#TextColor=B4B4B4
#TextFormat=%s

[Timer.EndingStartTime]
#TextVisible=No
#Precision=2
#TextPosX=10
#TextPosY=2
#TextAlign=0
#TextColor=B4B4B4
#TextFormat=%s Ending Start

[Timer.ExpectedTime]
#TextVisible=No
#Precision=2
#TextPosX=10
#TextPosY=19
#TextAlign=0
#TextColor=B4B4B4
#TextFormat=%s Expected