# Turbo
# Implements up to 30fps turbo for all controllers

# FramesOn is the number of frames to hold the button (1 or more)
# After that many frames, there will be one frame with the button released
# so the total length of each press is FramesOn + 1
# The fastest setting overall for speedrunning is 2 (the default),
# because codec lines usually take 3 frames to skip

# InputMask is a single hexadecimal number, where you add together
# the codes for each digital input you want to have turbo (including the d-pad)
# It's set to Tri/O/X/Sq by default (10 + 20 + 40 + 80 = F0)

# Toggle is a digital button or button combination that toggles turbo on or off
# By default it's set to L1 + R3 (1 + 400 = 401)

# See MGS2.README.txt for the full list of input codes

# You can create more than one turbo profile by creating more sections
# e.g. [Turbo.Profile.2]
# Each profile will inherit its settings from the previous profile

# You may also want to set up matching profiles in the TurboDisplay module
# to display different things for each profile

[Turbo]
Enabled=Yes
#Toggle=0401

[Turbo.Profile.1]
#EnabledAtStart=No
#FramesOn=2
#InputMask=00F0